name: tagam
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

  json_annotation: ^4.9.0
  dio: ^5.7.0
  provider: ^6.1.2
  get_it: ^8.0.2
  shared_preferences: ^2.3.3
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.15
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^6.9.0
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/



  fonts:
    - family: Gilroy
      fonts:
        - asset: fonts/gilroy/Gilroy-Regular.ttf
        - asset: fonts/gilroy/Gilroy-Bold.ttf
        - asset: fonts/gilroy/Gilroy-Medium.ttf
        - asset: fonts/gilroy/Gilroy-MediumItalic.ttf
        - asset: fonts/gilroy/Gilroy-Regular.ttf
        - asset: fonts/gilroy/Gilroy-SemiBold.ttf
        - asset: fonts/gilroy/Gilroy-Thin.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
